default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  pool: 10


development:
  <<: *default
  database: furulab_development

test:
  <<: *default
  database: furulab_test

production:
  adapter: mysql2
  database: furulab_production
  password: <%= ENV['ENTRY-MANAGEMENT-FURULAb_DATABASE_PASSWORD'] %>
  adapter: postgresql
